name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qt5-qmake libhdate-dev build-essential qttools5-dev-tools

    - name: Build
      run: |
        lrelease Luach.pro
        qmake Luach.pro
        make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luach-linux
        path: luach

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: luach
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        arch: 'win64_mingw81'

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-autotools
          autoconf-archive
          mingw-w64-x86_64-gettext

    - name: Build libhdate
      shell: msys2 {0}
      run: |
        git clone https://git.code.sf.net/p/libhdate/git libhdate
        cd libhdate
        autoreconf -i
        ./configure --prefix=/c/libhdate
        make
        make install

    - name: Build Luach
      shell: cmd
      run: |
        lrelease Luach.pro
        qmake Luach.pro
        mingw32-make

    - name: Deploy Qt
      shell: cmd
      run: |
        windeployqt release\luach.exe --dir release\
        copy C:\libhdate\bin\*.dll release\
        copy C:\libhdate\lib\*.dll release\

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'luach-windows.zip'
        directory: 'release'

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: luach-windows
        path: release/luach-windows.zip

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: release/luach-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
